/*
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tmapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import tmapi.model.EntitiesResponsePositions;

/**
 * EntitiesResponseEntities
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-12-20T13:29:48.384+03:00[Europe/Moscow]")
public class EntitiesResponseEntities {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private Map<String, Object> attributes = null;

  public static final String SERIALIZED_NAME_POSITIONS = "positions";
  @SerializedName(SERIALIZED_NAME_POSITIONS)
  private List<EntitiesResponsePositions> positions = null;

  public EntitiesResponseEntities type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Entity type
   * @return type
  **/
  @ApiModelProperty(example = "People", value = "Entity type")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public EntitiesResponseEntities attributes(Map<String, Object> attributes) {
    this.attributes = attributes;
    return this;
  }

  public EntitiesResponseEntities putAttributesItem(String key, Object attributesItem) {
    if (this.attributes == null) {
      this.attributes = new HashMap<String, Object>();
    }
    this.attributes.put(key, attributesItem);
    return this;
  }

   /**
   * Entity attributes. Depends on entity type
   * @return attributes
  **/
  @ApiModelProperty(example = "{\"Name\":\"Elvis Presley\",\"FirstName\":\"Elvis\",\"MiddleName\":\"\",\"LastName\":\"Presley\",\"NickName\":\"\",\"Attribute\":\"\",\"Postfix\":\"\",\"Age\":null,\"Gender\":\"Male\",\"Confidence\":0.9}", value = "Entity attributes. Depends on entity type")
  public Map<String, Object> getAttributes() {
    return attributes;
  }

  public void setAttributes(Map<String, Object> attributes) {
    this.attributes = attributes;
  }

  public EntitiesResponseEntities positions(List<EntitiesResponsePositions> positions) {
    this.positions = positions;
    return this;
  }

  public EntitiesResponseEntities addPositionsItem(EntitiesResponsePositions positionsItem) {
    if (this.positions == null) {
      this.positions = new ArrayList<EntitiesResponsePositions>();
    }
    this.positions.add(positionsItem);
    return this;
  }

   /**
   * Entity positions in text
   * @return positions
  **/
  @ApiModelProperty(value = "Entity positions in text")
  public List<EntitiesResponsePositions> getPositions() {
    return positions;
  }

  public void setPositions(List<EntitiesResponsePositions> positions) {
    this.positions = positions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntitiesResponseEntities entitiesResponseEntities = (EntitiesResponseEntities) o;
    return Objects.equals(this.type, entitiesResponseEntities.type) &&
        Objects.equals(this.attributes, entitiesResponseEntities.attributes) &&
        Objects.equals(this.positions, entitiesResponseEntities.positions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, attributes, positions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntitiesResponseEntities {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    positions: ").append(toIndentedString(positions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

