/*
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tmapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import tmapi.model.FactsResponsePositions;

/**
 * FactsResponseFacts
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-12-20T13:29:48.384+03:00[Europe/Moscow]")
public class FactsResponseFacts {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_ATTRIBUTES = "attributes";
  @SerializedName(SERIALIZED_NAME_ATTRIBUTES)
  private Map<String, Object> attributes = null;

  public static final String SERIALIZED_NAME_POSITIONS = "positions";
  @SerializedName(SERIALIZED_NAME_POSITIONS)
  private List<FactsResponsePositions> positions = null;

  public FactsResponseFacts type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Fact type
   * @return type
  **/
  @ApiModelProperty(example = "Occupation", value = "Fact type")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public FactsResponseFacts attributes(Map<String, Object> attributes) {
    this.attributes = attributes;
    return this;
  }

  public FactsResponseFacts putAttributesItem(String key, Object attributesItem) {
    if (this.attributes == null) {
      this.attributes = new HashMap<String, Object>();
    }
    this.attributes.put(key, attributesItem);
    return this;
  }

   /**
   * Fact attributes. Depends on fact type
   * @return attributes
  **/
  @ApiModelProperty(example = "{\"Person\":\"Elvis Presley\",\"Occupation\":\"American singer\",\"Confidence\":1}", value = "Fact attributes. Depends on fact type")
  public Map<String, Object> getAttributes() {
    return attributes;
  }

  public void setAttributes(Map<String, Object> attributes) {
    this.attributes = attributes;
  }

  public FactsResponseFacts positions(List<FactsResponsePositions> positions) {
    this.positions = positions;
    return this;
  }

  public FactsResponseFacts addPositionsItem(FactsResponsePositions positionsItem) {
    if (this.positions == null) {
      this.positions = new ArrayList<FactsResponsePositions>();
    }
    this.positions.add(positionsItem);
    return this;
  }

   /**
   * Fact positions in text
   * @return positions
  **/
  @ApiModelProperty(value = "Fact positions in text")
  public List<FactsResponsePositions> getPositions() {
    return positions;
  }

  public void setPositions(List<FactsResponsePositions> positions) {
    this.positions = positions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FactsResponseFacts factsResponseFacts = (FactsResponseFacts) o;
    return Objects.equals(this.type, factsResponseFacts.type) &&
        Objects.equals(this.attributes, factsResponseFacts.attributes) &&
        Objects.equals(this.positions, factsResponseFacts.positions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, attributes, positions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FactsResponseFacts {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    positions: ").append(toIndentedString(positions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

