/*
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tmapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * NotEnoughResourcesErrorError
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-12-20T13:29:48.384+03:00[Europe/Moscow]")
public class NotEnoughResourcesErrorError {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private Integer code;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public NotEnoughResourcesErrorError code(Integer code) {
    this.code = code;
    return this;
  }

   /**
   * The HTTP status code.
   * @return code
  **/
  @ApiModelProperty(example = "503", value = "The HTTP status code.")
  public Integer getCode() {
    return code;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public NotEnoughResourcesErrorError title(String title) {
    this.title = title;
    return this;
  }

   /**
   * The HTTP status description.
   * @return title
  **/
  @ApiModelProperty(example = "Service Unavailable", value = "The HTTP status description.")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public NotEnoughResourcesErrorError message(String message) {
    this.message = message;
    return this;
  }

   /**
   * A short, human-readable summary of the problem type.
   * @return message
  **/
  @ApiModelProperty(example = "Not enough resources to complete operation", value = "A short, human-readable summary of the problem type.")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotEnoughResourcesErrorError notEnoughResourcesErrorError = (NotEnoughResourcesErrorError) o;
    return Objects.equals(this.code, notEnoughResourcesErrorError.code) &&
        Objects.equals(this.title, notEnoughResourcesErrorError.title) &&
        Objects.equals(this.message, notEnoughResourcesErrorError.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, title, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotEnoughResourcesErrorError {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

