/*
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tmapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import tmapi.model.SentimentsResponseSentiments;

/**
 * SentimentsResponseDocuments
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-12-20T13:29:48.384+03:00[Europe/Moscow]")
public class SentimentsResponseDocuments {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_SENTIMENTS = "sentiments";
  @SerializedName(SERIALIZED_NAME_SENTIMENTS)
  private List<SentimentsResponseSentiments> sentiments = null;

  public SentimentsResponseDocuments id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Index of document in input documents array
   * @return id
  **/
  @ApiModelProperty(value = "Index of document in input documents array")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public SentimentsResponseDocuments sentiments(List<SentimentsResponseSentiments> sentiments) {
    this.sentiments = sentiments;
    return this;
  }

  public SentimentsResponseDocuments addSentimentsItem(SentimentsResponseSentiments sentimentsItem) {
    if (this.sentiments == null) {
      this.sentiments = new ArrayList<SentimentsResponseSentiments>();
    }
    this.sentiments.add(sentimentsItem);
    return this;
  }

   /**
   * Result of sentiments operation
   * @return sentiments
  **/
  @ApiModelProperty(value = "Result of sentiments operation")
  public List<SentimentsResponseSentiments> getSentiments() {
    return sentiments;
  }

  public void setSentiments(List<SentimentsResponseSentiments> sentiments) {
    this.sentiments = sentiments;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SentimentsResponseDocuments sentimentsResponseDocuments = (SentimentsResponseDocuments) o;
    return Objects.equals(this.id, sentimentsResponseDocuments.id) &&
        Objects.equals(this.sentiments, sentimentsResponseDocuments.sentiments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sentiments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SentimentsResponseDocuments {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sentiments: ").append(toIndentedString(sentiments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

