/*
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tmapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Sentiment attributes. Depends on sentiment type
 */
@ApiModel(description = "Sentiment attributes. Depends on sentiment type")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-12-20T13:29:48.384+03:00[Europe/Moscow]")
public class SentimentsResponseAttributes {
  public static final String SERIALIZED_NAME_SUBJECT = "Subject";
  @SerializedName(SERIALIZED_NAME_SUBJECT)
  private String subject;

  public static final String SERIALIZED_NAME_EVALUATION = "Evaluation";
  @SerializedName(SERIALIZED_NAME_EVALUATION)
  private String evaluation;

  public static final String SERIALIZED_NAME_OBJECT = "Object";
  @SerializedName(SERIALIZED_NAME_OBJECT)
  private String object;

  public static final String SERIALIZED_NAME_HEAD_OBJECT = "HeadObject";
  @SerializedName(SERIALIZED_NAME_HEAD_OBJECT)
  private String headObject;

  public static final String SERIALIZED_NAME_DEGREE = "Degree";
  @SerializedName(SERIALIZED_NAME_DEGREE)
  private Integer degree;

  public static final String SERIALIZED_NAME_ASPECT = "Aspect";
  @SerializedName(SERIALIZED_NAME_ASPECT)
  private String aspect;

  public static final String SERIALIZED_NAME_CONFIDENCE = "Confidence";
  @SerializedName(SERIALIZED_NAME_CONFIDENCE)
  private BigDecimal confidence;

  public SentimentsResponseAttributes subject(String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * Either the speaker himself or another person (a group of people) whose opinion is shared. The subject of evaluation is not always mentioned in a text, especially when we deal with informal texts, such as forums, blogs and social network posts. 
   * @return subject
  **/
  @ApiModelProperty(value = "Either the speaker himself or another person (a group of people) whose opinion is shared. The subject of evaluation is not always mentioned in a text, especially when we deal with informal texts, such as forums, blogs and social network posts. ")
  public String getSubject() {
    return subject;
  }

  public void setSubject(String subject) {
    this.subject = subject;
  }

  public SentimentsResponseAttributes evaluation(String evaluation) {
    this.evaluation = evaluation;
    return this;
  }

   /**
   * Implies the emotional judgment of a subject to some topic, an emotional reaction to something or the overall emotional tone of an utterance. Evaluation expresses an attitude of a subjeсt to a particular object, emotional response to something. 
   * @return evaluation
  **/
  @ApiModelProperty(value = "Implies the emotional judgment of a subject to some topic, an emotional reaction to something or the overall emotional tone of an utterance. Evaluation expresses an attitude of a subjeсt to a particular object, emotional response to something. ")
  public String getEvaluation() {
    return evaluation;
  }

  public void setEvaluation(String evaluation) {
    this.evaluation = evaluation;
  }

  public SentimentsResponseAttributes object(String object) {
    this.object = object;
    return this;
  }

   /**
   * It is something which is evaluated. Similar to the subject of evaluation, objects may not always be mentioned.
   * @return object
  **/
  @ApiModelProperty(value = "It is something which is evaluated. Similar to the subject of evaluation, objects may not always be mentioned.")
  public String getObject() {
    return object;
  }

  public void setObject(String object) {
    this.object = object;
  }

  public SentimentsResponseAttributes headObject(String headObject) {
    this.headObject = headObject;
    return this;
  }

   /**
   * The main words in a phrase.
   * @return headObject
  **/
  @ApiModelProperty(value = "The main words in a phrase.")
  public String getHeadObject() {
    return headObject;
  }

  public void setHeadObject(String headObject) {
    this.headObject = headObject;
  }

  public SentimentsResponseAttributes degree(Integer degree) {
    this.degree = degree;
    return this;
  }

   /**
   * It is used to refer to the degree of positive evaluation ranging from 1 to 5 (1-rather positivem 5 - extremely positive) and negative evaluation ranging from -1 to -5 (-1 rather negative, - 5 - extremely negative). 
   * minimum: -5
   * maximum: 5
   * @return degree
  **/
  @ApiModelProperty(value = "It is used to refer to the degree of positive evaluation ranging from 1 to 5 (1-rather positivem 5 - extremely positive) and negative evaluation ranging from -1 to -5 (-1 rather negative, - 5 - extremely negative). ")
  public Integer getDegree() {
    return degree;
  }

  public void setDegree(Integer degree) {
    this.degree = degree;
  }

  public SentimentsResponseAttributes aspect(String aspect) {
    this.aspect = aspect;
    return this;
  }

   /**
   * It is a word or phrase that defines what characteristic of the object is evaluated. It allows users to summarize different ways of expressing the same entity in one thematic section. 
   * @return aspect
  **/
  @ApiModelProperty(value = "It is a word or phrase that defines what characteristic of the object is evaluated. It allows users to summarize different ways of expressing the same entity in one thematic section. ")
  public String getAspect() {
    return aspect;
  }

  public void setAspect(String aspect) {
    this.aspect = aspect;
  }

  public SentimentsResponseAttributes confidence(BigDecimal confidence) {
    this.confidence = confidence;
    return this;
  }

   /**
   * It represents measure of how sure TM API Server in its conclusion. Confidence is measured on scale of 0.0 to 1.0.
   * minimum: 0
   * maximum: 1
   * @return confidence
  **/
  @ApiModelProperty(value = "It represents measure of how sure TM API Server in its conclusion. Confidence is measured on scale of 0.0 to 1.0.")
  public BigDecimal getConfidence() {
    return confidence;
  }

  public void setConfidence(BigDecimal confidence) {
    this.confidence = confidence;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SentimentsResponseAttributes sentimentsResponseAttributes = (SentimentsResponseAttributes) o;
    return Objects.equals(this.subject, sentimentsResponseAttributes.subject) &&
        Objects.equals(this.evaluation, sentimentsResponseAttributes.evaluation) &&
        Objects.equals(this.object, sentimentsResponseAttributes.object) &&
        Objects.equals(this.headObject, sentimentsResponseAttributes.headObject) &&
        Objects.equals(this.degree, sentimentsResponseAttributes.degree) &&
        Objects.equals(this.aspect, sentimentsResponseAttributes.aspect) &&
        Objects.equals(this.confidence, sentimentsResponseAttributes.confidence);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subject, evaluation, object, headObject, degree, aspect, confidence);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SentimentsResponseAttributes {\n");
    
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    evaluation: ").append(toIndentedString(evaluation)).append("\n");
    sb.append("    object: ").append(toIndentedString(object)).append("\n");
    sb.append("    headObject: ").append(toIndentedString(headObject)).append("\n");
    sb.append("    degree: ").append(toIndentedString(degree)).append("\n");
    sb.append("    aspect: ").append(toIndentedString(aspect)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

