/*
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tmapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SentimentsResponsePositions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-12-20T13:29:48.384+03:00[Europe/Moscow]")
public class SentimentsResponsePositions {
  public static final String SERIALIZED_NAME_SENTENCE = "sentence";
  @SerializedName(SERIALIZED_NAME_SENTENCE)
  private Integer sentence;

  public static final String SERIALIZED_NAME_BEGIN = "begin";
  @SerializedName(SERIALIZED_NAME_BEGIN)
  private Integer begin;

  public static final String SERIALIZED_NAME_LENGTH = "length";
  @SerializedName(SERIALIZED_NAME_LENGTH)
  private Integer length;

  public SentimentsResponsePositions sentence(Integer sentence) {
    this.sentence = sentence;
    return this;
  }

   /**
   * Sentence index
   * @return sentence
  **/
  @ApiModelProperty(value = "Sentence index")
  public Integer getSentence() {
    return sentence;
  }

  public void setSentence(Integer sentence) {
    this.sentence = sentence;
  }

  public SentimentsResponsePositions begin(Integer begin) {
    this.begin = begin;
    return this;
  }

   /**
   * Index of first token of sentiment
   * @return begin
  **/
  @ApiModelProperty(value = "Index of first token of sentiment")
  public Integer getBegin() {
    return begin;
  }

  public void setBegin(Integer begin) {
    this.begin = begin;
  }

  public SentimentsResponsePositions length(Integer length) {
    this.length = length;
    return this;
  }

   /**
   * Number of tokens in sentiment
   * @return length
  **/
  @ApiModelProperty(value = "Number of tokens in sentiment")
  public Integer getLength() {
    return length;
  }

  public void setLength(Integer length) {
    this.length = length;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SentimentsResponsePositions sentimentsResponsePositions = (SentimentsResponsePositions) o;
    return Objects.equals(this.sentence, sentimentsResponsePositions.sentence) &&
        Objects.equals(this.begin, sentimentsResponsePositions.begin) &&
        Objects.equals(this.length, sentimentsResponsePositions.length);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sentence, begin, length);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SentimentsResponsePositions {\n");
    
    sb.append("    sentence: ").append(toIndentedString(sentence)).append("\n");
    sb.append("    begin: ").append(toIndentedString(begin)).append("\n");
    sb.append("    length: ").append(toIndentedString(length)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

