/*
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tmapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import tmapi.model.TokensResponseSentences;

/**
 * TokensResponseDocuments
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-12-20T13:29:48.384+03:00[Europe/Moscow]")
public class TokensResponseDocuments {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_SENTENCES = "sentences";
  @SerializedName(SERIALIZED_NAME_SENTENCES)
  private List<TokensResponseSentences> sentences = null;

  public TokensResponseDocuments id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Index of document in input documents array
   * @return id
  **/
  @ApiModelProperty(value = "Index of document in input documents array")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public TokensResponseDocuments sentences(List<TokensResponseSentences> sentences) {
    this.sentences = sentences;
    return this;
  }

  public TokensResponseDocuments addSentencesItem(TokensResponseSentences sentencesItem) {
    if (this.sentences == null) {
      this.sentences = new ArrayList<TokensResponseSentences>();
    }
    this.sentences.add(sentencesItem);
    return this;
  }

   /**
   * List of sentences
   * @return sentences
  **/
  @ApiModelProperty(value = "List of sentences")
  public List<TokensResponseSentences> getSentences() {
    return sentences;
  }

  public void setSentences(List<TokensResponseSentences> sentences) {
    this.sentences = sentences;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TokensResponseDocuments tokensResponseDocuments = (TokensResponseDocuments) o;
    return Objects.equals(this.id, tokensResponseDocuments.id) &&
        Objects.equals(this.sentences, tokensResponseDocuments.sentences);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sentences);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TokensResponseDocuments {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sentences: ").append(toIndentedString(sentences)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

