/*
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tmapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TotalLimitPeriodic1Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-12-20T13:29:48.384+03:00[Europe/Moscow]")
public class TotalLimitPeriodic1Response {
  /**
   * A period when limitations apply
   */
  @JsonAdapter(NtUPeriod1Enum.Adapter.class)
  public enum NtUPeriod1Enum {
    SECOND("Second"),
    
    MINUTE("Minute"),
    
    HOUR("Hour"),
    
    DAY("Day"),
    
    MONTH("Month");

    private String value;

    NtUPeriod1Enum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static NtUPeriod1Enum fromValue(String text) {
      for (NtUPeriod1Enum b : NtUPeriod1Enum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + text + "'");
    }

    public static class Adapter extends TypeAdapter<NtUPeriod1Enum> {
      @Override
      public void write(final JsonWriter jsonWriter, final NtUPeriod1Enum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public NtUPeriod1Enum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return NtUPeriod1Enum.fromValue(String.valueOf(value));
      }
    }
  }

  public static final String SERIALIZED_NAME_NT_U_PERIOD1 = "NTUPeriod1";
  @SerializedName(SERIALIZED_NAME_NT_U_PERIOD1)
  private NtUPeriod1Enum ntUPeriod1;

  public static final String SERIALIZED_NAME_NT_U_IN_PERIOD1_LIMIT = "NTUInPeriod1Limit";
  @SerializedName(SERIALIZED_NAME_NT_U_IN_PERIOD1_LIMIT)
  private Integer ntUInPeriod1Limit;

  public static final String SERIALIZED_NAME_NT_U_IN_PERIOD1 = "NTUInPeriod1";
  @SerializedName(SERIALIZED_NAME_NT_U_IN_PERIOD1)
  private Integer ntUInPeriod1;

  public TotalLimitPeriodic1Response ntUPeriod1(NtUPeriod1Enum ntUPeriod1) {
    this.ntUPeriod1 = ntUPeriod1;
    return this;
  }

   /**
   * A period when limitations apply
   * @return ntUPeriod1
  **/
  @ApiModelProperty(value = "A period when limitations apply")
  public NtUPeriod1Enum getNtUPeriod1() {
    return ntUPeriod1;
  }

  public void setNtUPeriod1(NtUPeriod1Enum ntUPeriod1) {
    this.ntUPeriod1 = ntUPeriod1;
  }

  public TotalLimitPeriodic1Response ntUInPeriod1Limit(Integer ntUInPeriod1Limit) {
    this.ntUInPeriod1Limit = ntUInPeriod1Limit;
    return this;
  }

   /**
   * A maximum number of requests in the specified period
   * @return ntUInPeriod1Limit
  **/
  @ApiModelProperty(value = "A maximum number of requests in the specified period")
  public Integer getNtUInPeriod1Limit() {
    return ntUInPeriod1Limit;
  }

  public void setNtUInPeriod1Limit(Integer ntUInPeriod1Limit) {
    this.ntUInPeriod1Limit = ntUInPeriod1Limit;
  }

  public TotalLimitPeriodic1Response ntUInPeriod1(Integer ntUInPeriod1) {
    this.ntUInPeriod1 = ntUInPeriod1;
    return this;
  }

   /**
   * A number of requests that have already been processed
   * @return ntUInPeriod1
  **/
  @ApiModelProperty(value = "A number of requests that have already been processed")
  public Integer getNtUInPeriod1() {
    return ntUInPeriod1;
  }

  public void setNtUInPeriod1(Integer ntUInPeriod1) {
    this.ntUInPeriod1 = ntUInPeriod1;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TotalLimitPeriodic1Response totalLimitPeriodic1Response = (TotalLimitPeriodic1Response) o;
    return Objects.equals(this.ntUPeriod1, totalLimitPeriodic1Response.ntUPeriod1) &&
        Objects.equals(this.ntUInPeriod1Limit, totalLimitPeriodic1Response.ntUInPeriod1Limit) &&
        Objects.equals(this.ntUInPeriod1, totalLimitPeriodic1Response.ntUInPeriod1);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ntUPeriod1, ntUInPeriod1Limit, ntUInPeriod1);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TotalLimitPeriodic1Response {\n");
    
    sb.append("    ntUPeriod1: ").append(toIndentedString(ntUPeriod1)).append("\n");
    sb.append("    ntUInPeriod1Limit: ").append(toIndentedString(ntUInPeriod1Limit)).append("\n");
    sb.append("    ntUInPeriod1: ").append(toIndentedString(ntUInPeriod1)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

