/*
 * Megaputer Text Mining API
 * Megaputer Text Mining API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tmapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TotalLimitConstantResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-12-20T13:29:48.384+03:00[Europe/Moscow]")
public class TotalLimitConstantResponse {
  public static final String SERIALIZED_NAME_NT_U_LIMIT = "NTULimit";
  @SerializedName(SERIALIZED_NAME_NT_U_LIMIT)
  private Integer ntULimit;

  public static final String SERIALIZED_NAME_N_T_U = "NTU";
  @SerializedName(SERIALIZED_NAME_N_T_U)
  private Integer NTU;

  public TotalLimitConstantResponse ntULimit(Integer ntULimit) {
    this.ntULimit = ntULimit;
    return this;
  }

   /**
   * The maximum number of text units that can be processed in all time
   * @return ntULimit
  **/
  @ApiModelProperty(example = "250000", value = "The maximum number of text units that can be processed in all time")
  public Integer getNtULimit() {
    return ntULimit;
  }

  public void setNtULimit(Integer ntULimit) {
    this.ntULimit = ntULimit;
  }

  public TotalLimitConstantResponse NTU(Integer NTU) {
    this.NTU = NTU;
    return this;
  }

   /**
   * Counter of text units that have been already processed
   * @return NTU
  **/
  @ApiModelProperty(value = "Counter of text units that have been already processed")
  public Integer getNTU() {
    return NTU;
  }

  public void setNTU(Integer NTU) {
    this.NTU = NTU;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TotalLimitConstantResponse totalLimitConstantResponse = (TotalLimitConstantResponse) o;
    return Objects.equals(this.ntULimit, totalLimitConstantResponse.ntULimit) &&
        Objects.equals(this.NTU, totalLimitConstantResponse.NTU);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ntULimit, NTU);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TotalLimitConstantResponse {\n");
    
    sb.append("    ntULimit: ").append(toIndentedString(ntULimit)).append("\n");
    sb.append("    NTU: ").append(toIndentedString(NTU)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

